### ISSUE TITLE
It is possible to create an account with a username that exists

### ISSUE THREAD

**Issue by PatHock** [PatHock/Mice-tro#108]
As long as the password does not match an existing one...

**Comment by aredhouse** [comment]
working on this now

**Comment by aredhouse** [comment]
Hey @PatHock I added a method to check for a username in the database, can you make it actually work on the front end? I'm not sure how the new JSP's you set up work. If you have any problems with what I did feel free to ask for clarification!

**Comment by PatHock** [comment]
@aredhouse JSPs are plain HTML since EL notation doesn't work anymore. Functions related to passing data to and from the server are handled by Jquery in JavaScript. The JavaScript files import the CSS files, as well as any plugins (such as bootstrap) that are used. Webpack takes those files and creates a "bundle", which is the "entry point" in the jsp pages (the one .js file at the end of the body). To see the correlation between the .js files and the entry points, check out the webpackconfig.js (?) File in the root of our project.

**Comment by PatHock** [comment]
From AccountController:
```
public Account createAccount(String username, String password) {
        try {  
          Account newAccount = new Account(); 
          newAccount.setUsername(username);
          newAccount.setPassword(password);
          return newAccount;
      } catch (Exception e) {
          throw e;
      }
  }
```
* Need to check database to see if account with this username exists
* Try/catch block does nothing. Will investigate.

**Comment by aredhouse** [comment]
Added this method which searched the database for the input username to see if it already exists

+    public Boolean checkNewAccount(String username) {
+        Boolean isNewUsername = false;
+        List<Account> tempAccount;
+        tempAccount = db.findAccountByUsername(username);
+
+        if(tempAccount.size() == 1){
+            isNewUsername = true;
+        }
+
+        return isNewUsername;
+    }

**Comment by aredhouse** [comment]
I created this method to check if a username already exists in Account Controller. 

    //returns false if username already exists
    public Boolean checkNewAccount(String username) {
        Boolean isNewUsername = false;
        List<Account> tempAccount;
        tempAccount = db.findAccountByUsername(username);

        if(tempAccount.size() == 0){
            isNewUsername = true;
        }

        return isNewUsername;
    }

**Comment by PatHock** [comment]
971da28c20aab3063c7bc96fc278bbc333176aa0 Solves this issue.
